In [1]:
import pandas as pd
from bokeh.plotting import figure, output_file, show

In [2]:
df = pd.read_csv('twitchdata.csv')

In [3]:
print (df)

              Channel  Watch time(Minutes)  Stream time(minutes)  \
0               xQcOW           6196161750                215250
1            summit1g           6091677300                211845
2              Gaules           5644590915                515280
3            ESL_CSGO           3970318140                517740
4                Tfue           3671000070                123660
..                ...                  ...                   ...
995         LITkillah            122524635                 13560
996  빅헤드 (bighead033)            122523705                153000
997    마스카 (newmasca)            122452320                217410
998     AndyMilonakis            122311065                104745
999              Remx            122192850                 99180

     Peak viewers  Average viewers  Followers  Followers gained  Views gained  \
0          222720            27716    3246298           1734810      93036735
1          310998            25610    5310163           1370184      89705964
2          387315            10976    1767635           1023779     102611607
3          300575             7714    3944850            703986     106546942
4          285644            29602    8938903           2068424      78998587
..            ...              ...        ...               ...           ...
995         21359             9104     601927            562691       2162107
996          3940              793     213212             52289       4399897
997          6431              567     109068             -4942       3417970
998         10543             1153     547446            109111       3926918
999         13788             1205     178553             59432       2049420

     Partnered  Mature    Language
0         True   False     English
1         True   False     English
2         True    True  Portuguese
3         True   False     English
4         True   False     English
..         ...     ...         ...
995       True   False     Spanish
996       True   False      Korean
997       True   False      Korean
998       True   False     English
999       True   False      French

[1000 rows x 11 columns]

In [4]:
df_new=df.groupby("Language")

In [5]:
counts = df_new.count()
counts

,Channel,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature
Language,,,,,,,,,,
Arabic,5,5,5,5,5,5,5,5,5,5
Chinese,30,30,30,30,30,30,30,30,30,30
Czech,6,6,6,6,6,6,6,6,6,6
English,485,485,485,485,485,485,485,485,485,485
Finnish,1,1,1,1,1,1,1,1,1,1
French,66,66,66,66,66,66,66,66,66,66
German,49,49,49,49,49,49,49,49,49,49
Greek,1,1,1,1,1,1,1,1,1,1
Hungarian,2,2,2,2,2,2,2,2,2,2
Italian,17,17,17,17,17,17,17,17,17,17
Japanese,10,10,10,10,10,10,10,10,10,10
Korean,77,77,77,77,77,77,77,77,77,77
Other,1,1,1,1,1,1,1,1,1,1
Polish,12,12,12,12,12,12,12,12,12,12
Portuguese,61,61,61,61,61,61,61,61,61,61
Russian,74,74,74,74,74,74,74,74,74,74
Slovak,1,1,1,1,1,1,1,1,1,1
Spanish,68,68,68,68,68,68,68,68,68,68
Swedish,1,1,1,1,1,1,1,1,1,1
Thai,11,11,11,11,11,11,11,11,11,11
Turkish,22,22,22,22,22,22,22,22,22,22

In [11]:
countsIndex = list(counts.index)

- Get the the number of rows in the grouped by Language

In [6]:
counts.shape
counts.shape[0]

21

- Create a range from 0 to 21 as defined by the number of rows found
- Documentation on the built-in range() function from Dr. Silva --> https://docs.python.org/3/library/functions.html#func-range

In [7]:
range(counts.shape[0])

range(0, 21)

- Generate a list of each number in the range

In [8]:
list(range(counts.shape[0]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [9]:
countsList = list(counts)

- Set the x_range to the iundex of counts which are the country names

In [12]:
p = figure(x_range=countsIndex)

- Set the range list as the list of x values

In [13]:
x = list(range(counts.shape[0]))
y = counts['Watch time(Minutes)']
p.vbar(x,top=y)

GlyphRenderer(id='p1052', ...)

 - Generate the graph (now works, but the labels are very scrunched

In [14]:
show(p)